#!/bin/bash

if [ -z "$1" ]; then
  echo "# $0 float_ip/subnet target_ip"
  echo "# $0 10.2.3.4/24 192.168.0.1"
  exit 0
fi

IPS=${IPS:-"$1"}
TIP=${TIP:-"$2"}

# Tokenize and Testing Format
set -- "$IPS"
IFS="/"; declare -a Array=($*)

ETH=$(route -n | grep "^0.0.0.0" | tr ' ' '\n' | tail -1)


ip addr del ${Array[0]}/${Array[1]} dev ${ETH}
iptables-save | grep -v "IPFW_${Array[0]}" | iptables-restore
