- name: Install SmartOS update
  sudo: yes
  hosts: smartos

  tasks:
  - shell: wget -qO- https://raw.githubusercontent.com/ziozzang/build-dev-env/master/ubuntu/14.04/source-2.list > /etc/apt/sources.list
  - apt: update_cache=yes
  - apt: upgrade=dist
